config:
  azure-native:location: EastUS2
  senior-design-26:sqlAdminPassword:
    secure: AAABAHnWJuPHP2Jgq/skNjnnwtQyEvYix2NmqiR/5UdGYbEgY4Md3sgGIGexj0Qb
  senior-design-26:betterAuthSecret:
    secure: AAABAJE5AfhTO7l5NZDHskcj4z2ZwTo07rKD6pQLvzit5/5TzI4OLZvkXLNFNJy4
  senior-design-26:azureOpenAiApiKey:
    secure: AAABADYotb1FdbTQ5O3DZD/cYfTAfIzPuS2518XFyJpuQ6CXMhRoYEHuk85X+ra4RwaJW1YYDwQDtt3N7uKe/RVR/coh0OtVrkgL1Got+MaGiFNe5TwsuPEtqePjrRrOjo81nkiT/rA8iBesDJNGot6yUN0=
