config:
  azure-native:location: EastUS2
  senior-design-26:sqlAdminPassword:
    secure: AAABAHnWJuPHP2Jgq/skNjnnwtQyEvYix2NmqiR/5UdGYbEgY4Md3sgGIGexj0Qb
  senior-design-26:betterAuthSecret:
    secure: AAABAJE5AfhTO7l5NZDHskcj4z2ZwTo07rKD6pQLvzit5/5TzI4OLZvkXLNFNJy4
  senior-design-26:azureOpenAiApiKey:
    secure: AAABADYotb1FdbTQ5O3DZD/cYfTAfIzPuS2518XFyJpuQ6CXMhRoYEHuk85X+ra4RwaJW1YYDwQDtt3N7uKe/RVR/coh0OtVrkgL1Got+MaGiFNe5TwsuPEtqePjrRrOjo81nkiT/rA8iBesDJNGot6yUN0=
  senior-design-26:apnsKeyId:
    secure: AAABADkRAs5+OZprRK7tL5uLeHsa4Vnq5vHAKBa750iqKw1Th1hhitiW
  senior-design-26:apnsTeamId:
    secure: AAABAISR3CmoUJ3ClOBl4PAvv5WoAT9sd5UK2iY4fJQoIVwgA+Kgv6/h
  senior-design-26:apnsKeyContents:
    secure: AAABADyyJP6f8rlrKuGmRMQ/VoydXHAiYitK5fqiGkDnJfNKQh1HKnkVKV/220RJwzytQOKItyxYAOxkpDcB+unpfQts7qs/WRyitvaC+/IPyWa8uD8RnKZroNClYX6wbiqYjQNhTaNUfZahicusnH/lVi/PPs8wHv0UpijiPAY99HfglcXGYibYt1pycqm4OL1tGpXjtNBNCWELzF9oZwgGn3sgbA2fPphcs6bgkNuOGgK6lVd86zuIFoMRZRdg+ttHcPaake91nRwoWaiNaKPmwJRhWFbU6qqG7jPRjWVrW/eSxA9LXMcRIXWrkF+qwLfLxwBmZ90sAwx3C0P13lMJ2hOFmb/6AbSC3nX9Zg+m+YECIXZ9DZ4C71aFEuMXsjc=
